export const KEYS_MAP = {
  '0': '0', '1': '1', '2': '2', '3': '3', '4': '4', '5': '5', '6': '6', '7': '7', '8': '8', '9': '9',
  Power: 'Power', Eject: 'Eject', Abort: 'Abort', Help: 'Help', Backspace: 'Backspace', Tab: 'Tab',
  Numpad5: 'Numpad5', NumpadEnter: 'NumpadEnter', Enter: 'Enter', Pause: 'Pause', CapsLock: 'CapsLock',
  Escape: 'Escape', Convert: 'Convert', NonConvert: 'NonConvert', Space: 'Space', Numpad9: 'Numpad9',
  PageUp: 'PageUp', Numpad3: 'Numpad3', PageDown: 'PageDown', End: 'End', Numpad1: 'Numpad1',
  Home: 'Home', Numpad7: 'Numpad7', ArrowLeft: 'ArrowLeft', Numpad4: 'Numpad4', Numpad8: 'Numpad8',
  ArrowUp: 'ArrowUp', ArrowRight: 'ArrowRight', Numpad6: 'Numpad6', Numpad2: 'Numpad2',
  ArrowDown: 'ArrowDown', Select: 'Select', Open: 'Open', PrintScreen: 'PrintScreen',
  Insert: 'Insert', Numpad0: 'Numpad0', Delete: 'Delete', NumpadDecimal: 'NumpadDecimal',
  Digit0: 'Digit0', Digit1: 'Digit1', Digit2: 'Digit2', Digit3: 'Digit3', Digit4: 'Digit4',
  Digit5: 'Digit5', Digit6: 'Digit6', Digit7: 'Digit7', Digit8: 'Digit8', Digit9: 'Digit9',
  KeyA: 'KeyA', KeyB: 'KeyB', KeyC: 'KeyC', KeyD: 'KeyD', KeyE: 'KeyE', KeyF: 'KeyF',
  KeyG: 'KeyG', KeyH: 'KeyH', KeyI: 'KeyI', KeyJ: 'KeyJ', KeyK: 'KeyK', KeyL: 'KeyL',
  KeyM: 'KeyM', KeyN: 'KeyN', KeyO: 'KeyO', KeyP: 'KeyP', KeyQ: 'KeyQ', KeyR: 'KeyR',
  KeyS: 'KeyS', KeyT: 'KeyT', KeyU: 'KeyU', KeyV: 'KeyV', KeyW: 'KeyW', KeyX: 'KeyX',
  KeyY: 'KeyY', KeyZ: 'KeyZ', ContextMenu: 'ContextMenu', NumpadMultiply: 'NumpadMultiply',
  NumpadAdd: 'NumpadAdd', NumpadSubtract: 'NumpadSubtract', NumpadDivide: 'NumpadDivide',
  F1: 'F1', F2: 'F2', F3: 'F3', F4: 'F4', F5: 'F5', F6: 'F6', F7: 'F7', F8: 'F8',
  F9: 'F9', F10: 'F10', F11: 'F11', F12: 'F12', F13: 'F13', F14: 'F14', F15: 'F15',
  F16: 'F16', F17: 'F17', F18: 'F18', F19: 'F19', F20: 'F20', F21: 'F21', F22: 'F22',
  F23: 'F23', F24: 'F24', NumLock: 'NumLock', ScrollLock: 'ScrollLock',
  AudioVolumeMute: 'AudioVolumeMute', AudioVolumeDown: 'AudioVolumeDown',
  AudioVolumeUp: 'AudioVolumeUp', MediaTrackNext: 'MediaTrackNext',
  MediaTrackPrevious: 'MediaTrackPrevious', MediaStop: 'MediaStop',
  MediaPlayPause: 'MediaPlayPause', Semicolon: 'Semicolon', Equal: 'Equal',
  NumpadEqual: 'NumpadEqual', Comma: 'Comma', Minus: 'Minus', Period: 'Period',
  Slash: 'Slash', Backquote: 'Backquote', BracketLeft: 'BracketLeft',
  Backslash: 'Backslash', BracketRight: 'BracketRight', Quote: 'Quote',
  Props: 'Props', Cancel: 'Cancel', Clear: 'Clear', Accept: 'Accept',
  ModeChange: 'ModeChange', ' ': ' ', Print: 'Print', Execute: 'Execute',
  '\u0000': '\u0000', 'a': 'a', 'b': 'b', 'c': 'c', 'd': 'd', 'e': 'e',
  'f': 'f', 'g': 'g', 'h': 'h', 'i': 'i', 'j': 'j', 'k': 'k', 'l': 'l',
  'm': 'm', 'n': 'n', 'o': 'o', 'p': 'p', 'q': 'q', 'r': 'r', 's': 's',
  't': 't', 'u': 'u', 'v': 'v', 'w': 'w', 'x': 'x', 'y': 'y', 'z': 'z',
  '*': '*', '+': '+', '-': '-', '/': '/', ';': ';', '=': '=', ',': ',',
  '.': '.', '`': '`', '[': '[', '\\': '\\', ']': ']', "'": "'",
  Attn: 'Attn', CrSel: 'CrSel', ExSel: 'ExSel', EraseEof: 'EraseEof',
  Play: 'Play', ZoomOut: 'ZoomOut', ')': ')', '!': '!', '@': '@',
  '#': '#', '$': '$', '%': '%', '^': '^', '&': '&', '(': '(',
  'A': 'A', 'B': 'B', 'C': 'C', 'D': 'D', 'E': 'E', 'F': 'F',
  'G': 'G', 'H': 'H', 'I': 'I', 'J': 'J', 'K': 'K', 'L': 'L',
  'M': 'M', 'N': 'N', 'O': 'O', 'P': 'P', 'Q': 'Q', 'R': 'R',
  'S': 'S', 'T': 'T', 'U': 'U', 'V': 'V', 'W': 'W', 'X': 'X',
  'Y': 'Y', 'Z': 'Z', ':': ':', '<': '<', '_': '_', '>': '>',
  '?': '?', '~': '~', '{': '{', '|': '|', '}': '}', '"': '"',
  SoftLeft: 'SoftLeft', SoftRight: 'SoftRight', Camera: 'Camera',
  Call: 'Call', EndCall: 'EndCall', VolumeDown: 'VolumeDown',
  VolumeUp: 'VolumeUp', '\r': '\r', '\n': '\n'
} as const;

export const MODIFIER_KEYS_MAP = {
  ShiftLeft: 'ShiftLeft',
  ShiftRight: 'ShiftRight',
  ControlLeft: 'ControlLeft',
  ControlRight: 'ControlRight',
  AltLeft: 'AltLeft',
  AltRight: 'AltRight',
  MetaLeft: 'MetaLeft',
  MetaRight: 'MetaRight',
  Shift: 'Shift',
  Control: 'Control',
  Alt: 'Alt',
  Meta: 'Meta',
  AltGraph: 'AltGraph'
} as const;